{{- if .Values.serviceAccount.enabled }}
{{- range .Values.namespaces }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $.Values.serviceAccount.name }}
  namespace: {{ . }}
  annotations:
    azure.workload.identity/client-id: {{ $.Values.serviceAccount.clientId | quote }}
{{- end }}
{{- end }}
