apiVersion: v1
kind: ServiceAccount
metadata:
  name: coderaptor-workload-sa
  namespace: dev-codereviewer
  annotations:
    azure.workload.identity/client-id: "9a0d67f9-2147-4e65-9f2b-890884fff1d2"
