namespaces:
  - dev-codereviewer
replicaCount: 1
deploymentStrategy:
  type: RollingUpdate
  rollingUpdate:
    maxSurge: 0
    maxUnavailable: 1
image:
  registry: coderaptorproacrh476d.azurecr.io
  pullPolicy: Always
configMap:
  name: coderaptor-config
  data:
    AZURE_OPENAI_ENDPOINT: "https://ai-codereviewer-resource.openai.azure.com/"
    AZURE_OPENAI_DEPLOYMENT: "gpt-4.1-mini"
    AZURE_OPENAI_API_VERSION: "2025-01-01-preview"
    AUTH_SERVICE_URL: "http://auth-service:8001"
    EXECUTION_SERVICE_URL: "http://execution-service:8002"
    AI_SERVICE_URL: "http://ai-service:8003"
    REVIEW_SERVICE_URL: "http://review-service:8004"
secret:
  name: kv-secret
serviceAccount:
  enabled: true
  name: coderaptor-workload-sa
  clientId: "25eb44d6-459d-4081-af1a-250477f86646"
secretProviderClass:
  name: kv-secrets
  provider: azure
  userAssignedIdentityID: "25eb44d6-459d-4081-af1a-250477f86646"
  keyvaultName: coderaptor-prod-h476d-kv
  tenantId: e3d774dc-b8bb-4368-987e-c4738a1b89e1
services:
  auth:
    name: auth-service
    image: auth-service
    tag: 6d2a9ff8c7b4728b464744e6fd54aaf36c6ea471
    port: 8001
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
  execution:
    name: execution-service
    image: execution-service
    tag: 467a5ac35a882b09ff60c36b1a6ddd7c04b60b84
    port: 8002
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
  ai:
    name: ai-service
    image: ai-service
    tag: ea27a15e3bd7566f367ccbfe77e81ef157806144
    port: 8003
    resources:
      requests:
        cpu: 200m
        memory: 128Mi
  review:
    name: review-service
    image: review-service
    tag: 5df41fb0c793ac692731333257a831f87e7364b5
    port: 8004
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
  frontend:
    name: frontend
    serviceName: frontend-service
    image: frontend
    tag: 95fafc050e034c8aad35c738f2abc303a3de5207
    port: 8501
    resources:
      requests:
        cpu: 100m
        memory: 64Mi
keyvaultSync:
  enabled: true
  name: keyvault-secret-sync
  image: busybox:1.36
  replicaCount: 1
ingress:
  enabled: true
  namespace: dev-codereviewer
  name: codereviewer-ingress
  className: azure-application-gateway
  annotations:
    appgw.ingress.kubernetes.io/backend-protocol: "http"
    appgw.ingress.kubernetes.io/health-probe-path: "/_stcore/health"
    appgw.ingress.kubernetes.io/health-probe-port: "8501"
    appgw.ingress.kubernetes.io/health-probe-status-codes: "200-399"
    appgw.ingress.kubernetes.io/request-timeout: "60"
